### ISSUE TITLE
Move team data over to website API

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#101]
Move team/teammate data over to website API and then have the website pull that data from the API rather than the static data from the repo.

**Comment by ma2b0043** [comment]
@angle943 @ThaDeveloper what's the status of this issue?

**Comment by angle943** [comment]
@ThaDeveloper the models may need small tweakings based upon the recent talks @buckyroberts , @kristykjlee , and I had, but nothing should be major. Once those talks are finalized, I will let you know what those tweaks will be.

Independent of that, I will right now manually add `teams` and `teamMembers` in the database, and create a couple FE tasks

**Comment by ThaDeveloper** [comment]
> @ThaDeveloper the models may need small tweakings based upon the recent talks @buckyroberts , @kristykjlee , and I had, but nothing should be major. Once those talks are finalized, I will let you know what those tweaks will be.
> 
> Independent of that, I will right now manually add `teams` and `teamMembers` in the database, and create a couple FE tasks

Cool
