### ISSUE TITLE
Audit the website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#102]
Audit/review the website and see what information is out of date with our latest changes. For example I believe some of these documents are out of date https://thenewboston.com/teams/All/Resources

For any updates to the website that need to be made, create a ticket in the [website repo](https://github.com/thenewboston-developers/Website) so that the front-end team can update the website. If there are any design related updates required, create a ticket in the [design repo](https://github.com/thenewboston-developers/Design) first.

**Comment by ma2b0043** [comment]
Should I wait for the new designs to be implemented or should I just carry on my work?

**Comment by ma2b0043** [comment]
@buckyroberts should we close this now as everything is being audited update by update or should we keep this open so that once everything is complete we can have a final audit of the website(which may by difficult seeing as we keep on updating the website)
