### ISSUE TITLE
Write detailed requirements for new Activity Report

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#103]
Go through the [updated payment and distribution updates](https://docs.google.com/document/d/1CNqMZWCoxOguu8OHF-xpkyww7NIsGwmTmtJaHEqZa9E/edit?usp=sharing) and write up a detailed set of requirements on exactly what should be included in our new Activity Report format.

A sample Activity Report would be great as well. Once everything is finalized including the new "Acceptable Proof of Work" documentation we (Audit Team + Government) can review together and then once everything is good, share with with the community and post it on the website.

**Comment by buckyroberts** [comment]
@ma2b0043 Where are these docs?

**Comment by ma2b0043** [comment]
I already shared the docs with you on discord. I'm attaching the document here as well:

https://docs.google.com/document/d/19UvDKAMGBxwuo3PqctcuopMSK4DxGtMiqkTMIJLpjJc/edit#heading=h.z7isv0y64qha

If you need access, kindly message @javina89 as well.

**Comment by tomijaga** [comment]
The doc is titled "weekly report", it would be better if it was titled "milestone report" to reflects the recent updates
