### ISSUE TITLE
Gather community feedback

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#108]
Gather feedback from the community about _anything_ that we can make better. No need to send out surveys or anything, just read through the chats to see if any community member has any useful feedback about the project or the community.

**Comment by Chrisha1212** [comment]
https://docs.google.com/spreadsheets/d/1y90pVWN6t1MCIrxUqHz0sqDbX0YA3QsT2sFAEpWys8k/edit#gid=0

**Comment by Prawesh-MAGNETIC** [comment]
1. we need to have a Wikipedia page for @buckyroberts as we South-Asians solely rely on wiki info for Authentication.

**Comment by manishram** [comment]
@Prawesh-MAGNETIC
Agreed but didn't like the "rely on wiki info for Authentication" part! 😅

Information on the Wikipedia page should not be confused with authenticity. It barely takes a month or two to get on top wiki writers. People have tried to spread lots of fake info on Wikipedia in past. In fact a few months back someone edited a page of the tournament with the winner team name even before the tournament ended because he/she was supporter of that team, creating chaos on social media. Later it got rectified with **Winner: TBD**

**Comment by Prawesh-MAGNETIC** [comment]
@manishram   Noted sir.! 
Many Students and Teenagers trust and believe the wiki page blindly.
I have seen many people presenting ppt, Docx, and paper referring to Wikipedia.!

**Comment by Chrisha1212** [comment]
> 1. we need to have a Wikipedia page for @buckyroberts as we South-Asians solely rely on wiki info for Authentication.
> 2. meme should continue, the meme is the best way to promote Brands.
> 3. I with my tweeter handle @PraweshMAGNETIC, am doing my best to promote #TNBC
> 
> https://twitter.com/PraweshMAGNETIC/status/1373663031125704704?s=20

We are currently working on marketing road map and probably we are going to talk about it but anyway thank you for this suggestions.

**Comment by Prawesh-MAGNETIC** [comment]
As our Team believes in equality, but why the FAUCET (tweet) coin distribution is varying from 48, 50, and 52?
some A/c received 48, 50 and 52.?
![Screenshot (98)](https://user-images.githubusercontent.com/71756108/112412541-ae824e80-8d44-11eb-817e-7eecc48241f6.png)
![Screenshot (99)](https://user-images.githubusercontent.com/71756108/112412544-b04c1200-8d44-11eb-8b89-627dfd896b17.png)

@Chrisha1212 @buckyroberts

**Comment by tomijaga** [comment]
@manishram 
> Agreed but didn't like the "rely on wiki info for Authentication" part! 😅

You can have a wiki run by **thenewboston** team that is not hosted on wikipedia. 
This way the team or a select group of people can verify the content that is posted on the wiki.

**Comment by ma2b0043** [comment]
@Chrisha1212 whats the status of this issue? should we close this now?
