### ISSUE TITLE
Move Aayushi Maheshwari to Front-end Team

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#11]
Aayushi Maheshwari mentioned that she would like to be part of the Front-end team (since she is a software developer in real life). So we need to:
- update her team information in the `Payment-Processor` repo
- move her to the Front-end team on the website

**Comment by rahul-kothari** [comment]
@lapstjup @odetolataiwo @Hristijan95 could you guys look into this please?

**Comment by lapstjup** [comment]
@rahul-kothari Cool I will update her details on the website.

**Comment by lapstjup** [comment]
Done. @rahul-kothari Currently I have set the `isLead` to false but she was a lead for Slack Manager. What do you think about it ?

**Comment by rahul-kothari** [comment]
you guys are the front end team - your decision. Do you guys really need so many FE Leads? If not you can leave `isLead` to `false`. Can always change it if/when you guys think you need more leads. Up to you!
