### ISSUE TITLE
Complete "Team Payment Updates" document and guidelines

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#110]

**Comment by ma2b0043** [comment]
Who's working on this?

**Comment by buckyroberts** [comment]
https://docs.google.com/document/d/1CNqMZWCoxOguu8OHF-xpkyww7NIsGwmTmtJaHEqZa9E/edit?usp=sharing

@ma2b0043 can you work with @kristykjlee @angle943 and the audit team on it? Once all the details are finalized we can get designs for it and add it to the website similar to how we did with all the project updates here https://thenewboston.com/projects/overview

**Comment by ma2b0043** [comment]
Yeah sure.

**Comment by ma2b0043** [comment]
@kristykjlee do we close this now?

**Comment by kristykjlee** [comment]
> @kristykjlee do we close this now?

Closed
