### ISSUE TITLE
Add "Member Conduct and Work Rules Policy" to website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#111]
Add the following "Member Conduct and Work Rules Policy" document to website. Check with @kristykjlee to figure out where on the website it should go. Afterwards, create a ticket for the front-end team in the `Website` repo to add it.

https://docs.google.com/document/d/1OL1096HgVxIwVWhtv9fqmwcavBesx6YrkH0tTyeQ-LM/edit?usp=sharing

**Comment by ma2b0043** [comment]
Okay, got it, will start working on it as soon as possible.

**Comment by ma2b0043** [comment]
Waiting for this to be finished:

https://github.com/thenewboston-developers/Design/issues/172

Once I've got the design, I'll pass this onto to FE team.

**Comment by ma2b0043** [comment]
This task has been completed and updated on website:

https://thenewboston.com/guidelines

If you are okay with it, should we close this?
