### ISSUE TITLE
Update application process on website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#112]
Work with @Chrisha1212 to update our application process on the website. For every job posting we will direct the user to a Google form where they can fill out all of their information. Once submitted, the form will be available to @Chrisha1212 for review.

Once the form is built and working, meet with @kristykjlee to see what (if any) updated designs are needed and then write up a ticket on the `Website` repo so the front-end team can update the website.

Note to @Chrisha1212 and @ma2b0043 - we also need to include an input in the form to know which position they are applying for since there will likely be multiple job openings on the website.

Job application template doc - https://docs.google.com/document/d/1fyMjGZzmAF-8KnWftQdBl-OJcbCsTYX1xaV22LVvUIo/edit?usp=sharing
Google forms tutorial - https://www.youtube.com/watch?v=BtoOHhA3aPQ

**Comment by ma2b0043** [comment]
Got it, will start working on asap.

**Comment by ma2b0043** [comment]
I've created the form, waiting for @kristykjlee to review it. @Chrisha1212 has already reviewed it, as well.

**Comment by ma2b0043** [comment]
Waiting for the following issue to be completed:

https://github.com/thenewboston-developers/Design/issues/167

**Comment by ma2b0043** [comment]
> Waiting for the following issue to be completed:
> 
> [thenewboston-developers/Design#167](https://github.com/thenewboston-developers/Design/issues/167)

This issue has been closed, passing the design to the FE team, once that issue is closed then I'll close this issue as well.
