### ISSUE TITLE
Find DevOps for Website-API

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#116]
Find DevOps for Website-API to set up CI/CD.

Note: If @ThaDeveloper is familiar with CI/CD he can lead our DevOps as well.

**Comment by ThaDeveloper** [comment]
I'm familiar but not much experienced/well-versed to lead a DevOps team.

**Comment by buckyroberts** [comment]
@ThaDeveloper that is fine for now. We can get everything up and running for now and look for a dedicated DevOps engineer as well.
