### ISSUE TITLE
Add community roadmap to the website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#118]
Create, design, and add a roadmap to the website.

**Comment by ma2b0043** [comment]
I discussed this with tristan about this and we came up with a few ideas about the roadmap, linking the document here:

https://docs.google.com/document/d/1cXl43LStJKzdvBwxhndezOjV4_I0HmKPT_p9Ewu1F7k/edit?usp=sharing

Me and @Chrisha1212 will write the necessary parts of the doc and once we're done I'll ask Mr K. or @pitchapa-n to make a design for the FE team.

**Comment by ma2b0043** [comment]
Working on the overall structure of this roadmap with tristan and chrisha. You can view our progress in the following doc:

https://docs.google.com/document/d/1cXl43LStJKzdvBwxhndezOjV4_I0HmKPT_p9Ewu1F7k/edit?usp=sharing

Once we are done and have written everything up, Pitchapa or Mr K. will make the design for the FE team.

**Comment by ma2b0043** [comment]
We should unassign pitchapa and add Kashif Ahmad or @kristykjlee to this task.

**Comment by buckyroberts** [comment]
@ma2b0043 when I have things to review like these docs would you mind writing me up a ticket and adding it to the [Education project](https://github.com/thenewboston-developers/Management/projects/10)? Otherwise things end up getting lost in my notifications.

**Comment by buckyroberts** [comment]
> We should unassign pitchapa and add Kashif Ahmad or @kristykjlee to this task.

@ma2b0043 feel free to do these things when they need done - no need to wait for me

**Comment by ma2b0043** [comment]
> @ma2b0043 When I have things to review like these docs do you mind adding these tickets to the [Education project](https://github.com/thenewboston-developers/Management/projects/10)? Otherwise things end up getting lost in my notifications.
> 
> <img alt="Screen Shot 2021-04-15 at 7 58 13 PM" width="329" src="https://user-images.githubusercontent.com/8547538/114965190-fc124880-9e24-11eb-8557-45a226e043b7.png">

Got it.

**Comment by buckyroberts** [comment]
**Main Docs**
https://docs.google.com/document/d/1cXl43LStJKzdvBwxhndezOjV4_I0HmKPT_p9Ewu1F7k/edit

**Blockchain**
https://github.com/thenewboston-developers/thenewboston-node/issues/146

**Outline**
https://docs.google.com/document/d/1t5kEB_Z6E8Bi1xqw8ORNAk3aLaOxY6Zvjf99DIT4HeA/edit

**Notes**
https://docs.google.com/document/d/1LBEpWHWidayKtF38rMZczVEY0yXxfKH94TW0jFChmKA/edit
