### ISSUE TITLE
Create standardized biweekly update template

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#119]
Create standardized biweekly update template. We will use this format for all of our future biweekly updates to keep things consistent.

**Comment by Chrisha1212** [comment]
https://docs.google.com/document/d/1Nj0xeu7ZE2ZGU3riUs_5Al_c4zIkMv3mYHmem1k7EiI/edit

**Comment by Chrisha1212** [comment]
> https://docs.google.com/document/d/1Nj0xeu7ZE2ZGU3riUs_5Al_c4zIkMv3mYHmem1k7EiI/edit

Still in progress

**Comment by ma2b0043** [comment]
Its completed. Waiting for your review @buckyroberts 

https://docs.google.com/document/d/1Nj0xeu7ZE2ZGU3riUs_5Al_c4zIkMv3mYHmem1k7EiI/edit?usp=sharing

**Comment by buckyroberts** [comment]
Closing - this will be replaced with our newsletter
