### ISSUE TITLE
Figure out the technicalities for the Feedback page, FAQ, & Contact Us

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Management#123]
@ma2b0043 Would you be able to figure out the technicalities for the Feedback page, FAQ, & Contact Us?

**Feedback page considerations**
- How should the user submit feedback? Where should all the submissions live?
- Should we make this public or private?
- Should we make this 1-way or 2-way?
- etc

**Contact Us page considerations**
- How do we make sure people dont come to this page to send us Feedback?
- Where should all the submissions live?
- etc

**FAQ page considerations**
- How will we decide what is an FAQ?
- What are the FAQs we need to add at this moment?
- What are the different categories we can include?
- etc

![FeedBack](https://user-images.githubusercontent.com/68207101/112714707-d5519980-8e98-11eb-81d9-28b99682a5fe.jpg)
![Contact Us](https://user-images.githubusercontent.com/68207101/112714712-da164d80-8e98-11eb-8291-0d7599d702dc.jpg)
![FAQ](https://user-images.githubusercontent.com/68207101/112714711-d8e52080-8e98-11eb-8aff-dc4238b9c862.jpg)

**Comment by ma2b0043** [comment]
Sure I'll give it a go. If I need some help, I'll contact you.

**Comment by ma2b0043** [comment]
I've added some suggested solutions, to your queries in the document below:

https://docs.google.com/document/d/1vnAkCEpagBH9YbadcS9RvlfQN8L_AzfirySQDIpg3oA/edit?usp=sharing

 Can you take a look at it?

**Comment by ma2b0043** [comment]
@kristykjlee can we close this now?

**Comment by kristykjlee** [comment]
@ma2b0043 Done!
