### ISSUE TITLE
Create technical roadmap

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#126]
Create a technical roadmap so that the core team has a way to keep track of all high level tasks needed to reach beta. This will include blockchain, backend, frontend, design, etc... tasks.

**Example:**
![homepage-sw](https://user-images.githubusercontent.com/8547538/112766993-2fea1300-8fc9-11eb-8f95-47bb1fae722e.png)

**Comment by ma2b0043** [comment]
Got it, if I need any help, I'll contact you.

**Comment by ma2b0043** [comment]
Can you pause or close this, as we dont really need it right now.
