### ISSUE TITLE
Milestones for team page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#140]
## Overview

To better improve the transparency around the tasks each team is working on we will be adding “milestones” to each team page. We will be using the data that already exists from the GitHub API.

## For Design

Each of our milestones will be titled “Sprint #” and will also include a description and a due date. An example milestone can be seen here https://github.com/thenewboston-developers/Management/milestone/1

We would like to display the following information.

**Sprint information**
- title (ie. “Sprint 26”)
- progress bar
- due date
- description

**For each issue**
- title
- status (open/closed)
- issue number, date open/closed, and creators username (ie. “#128 opened 7 days ago by buckyroberts”)
- assignee(s)

As always, the designs should also be responsive.

## For Engineering

Milestones - https://api.github.com/repos/thenewboston-developers/Management/milestones
Issues - https://api.github.com/repos/thenewboston-developers/Management/issues?milestone=1&state=all

**Resources**
GitHub milestone overview - https://docs.github.com/en/github/managing-your-work-on-github/about-milestones
Short YouTube overview - https://www.youtube.com/watch?v=ukYSRu4k0gs

**Comment by jamessspanggg** [comment]
hi @buckyroberts, how are we determining the duration? do we use `due date - 7` as the start date? Also, i assume that the `number` field will be for the week number?

<img width="543" alt="Screen Shot 2021-04-25 at 4 48 55 PM" src="https://user-images.githubusercontent.com/32864116/115987075-22cf3c80-a5e6-11eb-8b97-4f3ee2f3f72b.png">

**Comment by jamessspanggg** [comment]
@buckyroberts are we adding milestones to each repo? or we define each team's milestone all in the management repo?

**Comment by ma2b0043** [comment]
Completed: https://thenewboston.com/progress
