### ISSUE TITLE
Write up ticket for DevOps

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#141]
Work with @truyenhv to write up ticket for DevOps. This new team was added half way through our first trial sprint so we did not create any tickets for them during sprint planning.

Once they have been written we can add them to the DevOps project board https://github.com/thenewboston-developers/DevOps/projects/1

Note: I already spoke with @truyenhv over Discord and discussed some of the initial tasks to work on so he will have a record of those. There may be some additional tasks that @ThaDeveloper may know of so you can check with him as well.

**Comment by ma2b0043** [comment]
should we close this now? as truyen knows how to work with GitHub issue.

**Comment by ma2b0043** [comment]
@buckyroberts can we close this issue? as truyen can create his own devops issues now
