### ISSUE TITLE
Team Member Payment Process

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#142]
After reading through the attached documentation:

1. Review the payment process with @Chrisha1212
2. Set up a payment account separate from your personal account so that we can monitor/audit the timesheets payments
3. Send me or @kristykjlee your payment account so that we can fund it
4. Have @Chrisha1212 start sending out payments for all Approved timesheets
5. Send the documentation and graphics through the Design team and then the Front-end team to add it to the website

**Documentation** - https://docs.google.com/document/d/1t-h2sfQBamZe7nWSPe2NbIQR7B90iMZWHXAohwgul94/edit?usp=sharing

**Graphics** - [TeamMemberPaymentGraphics.zip](https://github.com/thenewboston-developers/Management/files/6293038/TeamMemberPaymentGraphics.zip)

**Comment by ma2b0043** [comment]
Bucky, can you explain "Send the documentation and graphics through the Design team and then the Front-end team to add it to the website", like are we supposed to show a 'sample payment process' on the website?

**Comment by ma2b0043** [comment]
Created the Contributor Payment Account: b4b296b2d838a634158dcf03a7a340be428206bf9bfda56adb1a33b9d5635b32

**Comment by ma2b0043** [comment]
@buckyroberts we have successfully implemented this process, should we close this now or keep it open?
