### ISSUE TITLE
Weekly feedback report

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#143]
Every week, prepare a feedback report including all questions, comments, feedback that may be useful towards improving our network and/or our community. Share this with the governors every Wednesday. Look for feedback across all social media channels including Discord.

Here is the template we can use - https://docs.google.com/document/d/1i0u2XATkaFdkY47I0wEoap_eCnyCgCZ1SAuOrv7tgr4/edit?usp=sharing

To create a new report, make a copy of the existing template.

<img width="496" alt="Screen Shot 2021-04-11 at 6 44 13 PM" src="https://user-images.githubusercontent.com/8547538/114330163-f996b280-9af5-11eb-8057-4da96a98c221.png">

**Comment by Chrisha1212** [comment]
Requesting for Access

**Comment by Chrisha1212** [comment]
https://docs.google.com/document/d/1vfg_JKVi7XT3fj06ZYo1jvuLcC5sT4C1jz1HQNzTzhQ/edit#

**Comment by Chrisha1212** [comment]
https://drive.google.com/drive/u/1/folders/18fpNZMF1SHV5lGlDpXuFv-cFAFiYO6NV

**Comment by ma2b0043** [comment]
@buckyroberts can we close this issue now?
