### ISSUE TITLE
Create standardized "Sprint Planning" template

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#145]
Create standardized template for our Sprint Planning notes to follow this formatting:
- [Meeting Notes](https://docs.google.com/document/d/15P7MPPGgC2O3ZhOWryOeuW1K5EO9TL8_TBWR4Z2-_eo/edit?usp=sharing)
- [Community Feedback Report](https://docs.google.com/document/d/1i0u2XATkaFdkY47I0wEoap_eCnyCgCZ1SAuOrv7tgr4/edit?usp=sharing)
- [Team Feedback Report](https://docs.google.com/document/d/11ha_3Qs38DXprpuCrpL0XELw9-hUWlaI2u5heusgb24/edit?usp=sharing)

Here are the existing Sprint Planning notes that we need to standardize and create a template for:
- https://docs.google.com/document/d/1Xspw8GyoJeQwERKJsFexZFd-DaFxh5YHLv0t7gRPflY/edit?usp=sharing
- https://docs.google.com/document/d/1Y-hgS59NrzQHxcRomV_KrntkQa3WD7JWe2iGXBF2gOo/edit?usp=sharing

**Comment by Chrisha1212** [comment]
https://docs.google.com/document/d/1Xspw8GyoJeQwERKJsFexZFd-DaFxh5YHLv0t7gRPflY/edit#

**Comment by Chrisha1212** [comment]
https://docs.google.com/document/d/1Y-hgS59NrzQHxcRomV_KrntkQa3WD7JWe2iGXBF2gOo/edit?usp=sharing

**Comment by ma2b0043** [comment]
@Chrisha1212 @buckyroberts should we close this?
