### ISSUE TITLE
Add Terms of Use and Privacy Policy to the website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#146]
Add Terms of Use and Privacy Policy to the website.
1. Send through design for styling, links, where they want it on the website, etc...
2. Once design is finished create a ticket for the frontend team to add to the website

**Documents**
- [Privacy Policy.docx](https://github.com/thenewboston-developers/Management/files/6312479/Privacy.Policy.docx)
- [Terms of Use.docx](https://github.com/thenewboston-developers/Management/files/6312480/Terms.of.Use.docx)

**Comment by ma2b0043** [comment]
Okay, I'll start working on this from tomorrow.

**Comment by tspearing** [comment]
Privacy Policy:
1) "This privacy policy (“Policy”) describes how thenewboston in California" Is thenewboston registered in California or a different state?
2) At the bottom it states "please contact us through the information listed on our website" and then "You may contact us in writing or through our website". However, it doesn't state which email address to use or a physical address. If we need a physical address, get a PO box.

Terms:
1) Feels like this was written for a social media platform, not a crypto. For example: "You hereby affirm we have the right to determine whether any of your User Content submissions are appropriate and comply with these Terms of Service, remove any and/or all of your submissions, and terminate your account with or without prior notice." If someone writes an offensive memo, we can't delete it or remove them.
2) "If you become aware of misuse of our Service, please contact us at https://thenewboston.com." Should this be an email address?
3) "The Company has adopted and implemented a policy that provides for the termination in appropriate circumstances of users of the Service who are repeat infringers " Once again, you can't kick people off a blockchain. Feels very social media-ish.
4) "(b) Take-Down Notices" and "(c) Counter-Notices" We can't get into the business of removing memos from the blockchain or putting them back.
5) I've heard of companies having a mandatory arbitration clause but don't see one in our terms. more info:  https://techcrunch.com/2012/03/20/netflix-doesnt-want-you-to-sue-them-according-to-new-terms-of-service/ https://www.investopedia.com/terms/m/mandatory-binding-arbitration.asp

**Comment by ma2b0043** [comment]
@buckyroberts should we close this for now? as its dependent on this: https://github.com/thenewboston-developers/Management/issues/160 .
