### ISSUE TITLE
Add playlists & videos to website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#165]
Add all **educational** (excluding video game and other non-educational content) playlists & videos from thenewboston YouTube channel to the website. The videos section is now live, we just need to populate it with content now https://thenewboston.com/tutorials/All

It may be easiest to create a tool/script for this rather than having to add each video via Django admin. Check with @ThaDeveloper to figure out the best way to bulk upload multiple videos at once.

---

![screencapture-studio-youtube-channel-UCJbPGzawDH1njbqV-D5HqKw-playlists-2021-05-02-19_29_48](https://user-images.githubusercontent.com/8547538/116836888-31d16400-ab7d-11eb-9e16-a43828208c5d.png)

---

![screencapture-studio-youtube-channel-UCJbPGzawDH1njbqV-D5HqKw-playlists-2021-05-02-19_30_07](https://user-images.githubusercontent.com/8547538/116836893-35fd8180-ab7d-11eb-8d84-1e63cb279e9a.png)

**Comment by ma2b0043** [comment]
Got it!
