### ISSUE TITLE
Payment Integrations

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#190]
#### Feature description
Various payment integrations to work with the beta blockchain network. This can also be split up into multiple features if needed.

#### What problem(s) does this solve?
Right now there is no easy way to accept TNBC for goods and services without having to manually program a custom solution.

#### Goals and objectives
Provide websites, platforms, store owners, and users a way to accept TNBC for their goods and services.

#### What teams/individuals will be involved in the project?
Not sure yet. Still deciding whether to develop this under the core team or as a project.

#### Expected output/deliverables
A variety of integrations that enables websites to easily accept TNBC.

#### User stories
As a owner of an online store I would like to accept TNBC for my goods and services.

**Comment by ma2b0043** [comment]
@manishram @bojan-ilijevski @tspearing we need to research on a way to enable this for thenewboston coins. 

I'm sharing a document here, where we can add our research work and discuss it as well. Link:  https://docs.google.com/document/d/1JTOUXuFVJ3Bx66IFTS8bXM4ozlSu2KGh2yvPnkn6TPY/edit?usp=sharing

**Comment by buckyroberts** [comment]
@ma2b0043 just had a meeting with @manishram and @tspearing. They can fill you in on the next steps.
