### ISSUE TITLE
Fix task labels

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#217]
Certain labels are using time instead of coins which cause the values to be incorrect on the website. All coin value labels should be quantified in coins only, not time.

---

<img width="1042" alt="Screen Shot 2021-05-29 at 8 11 31 PM" src="https://user-images.githubusercontent.com/8547538/120090823-49d3cf00-c0ba-11eb-910f-86ae342e7cf1.png">

---

<img width="372" alt="Screen Shot 2021-05-29 at 8 11 44 PM" src="https://user-images.githubusercontent.com/8547538/120090824-4b04fc00-c0ba-11eb-89fb-e8411899b4bf.png">

---

**Example Issue**
- https://github.com/thenewboston-developers/thenewboston-js/issues/153

**Comment by ma2b0043** [comment]
I'll start working on this today.

**Comment by ma2b0043** [comment]
I have changed the labels from these repo's:

1. https://github.com/thenewboston-developers/thenewboston-js/issues/labels

All other repo's dont have any sort of labels which relate to time.

**Comment by ma2b0043** [comment]
Will the website needs to be manually changed(by FE) or are the labels on the website automatically changed via website-api?
