### ISSUE TITLE
Add projects to the website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#218]
Add the following projects to the website using Django admin. Note that in order to create a `Project` you must first create a `Project team` and then a `Project member`.

- [Kotlin Multiplaform Mobile SDK](https://github.com/thenewboston-developers/Projects/issues/169)
- [TNBpay](https://github.com/thenewboston-developers/Projects/issues/172)
- [Hierarchical deterministic (HD) Wallets for TNB](https://github.com/thenewboston-developers/Projects/issues/198)
- [TNBAnon](https://github.com/thenewboston-developers/Projects/issues/201)
- [TNB Minecraft Integration](https://github.com/thenewboston-developers/Projects/issues/206)
- [tnbGo](https://github.com/thenewboston-developers/Projects/issues/212)

**Comment by ma2b0043** [comment]
Done. Can you check the website?
