### ISSUE TITLE
Get GitHub account for all team members

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#22]
For all team members without a GitHub username, message them on Slack to get their GitHub username. You can see which team members are missing that information by visiting https://thenewboston.com/teams

Post each of their GitHub usernames here when complete.

Update: Related PR https://github.com/thenewboston-developers/Website/pull/1081

**Comment by Chrisha1212** [comment]
David Yap-davidyapdy

**Comment by Chrisha1212** [comment]
Bojan Ilijevski-bojan_007

**Comment by Chrisha1212** [comment]
Rahul Kothari - rahul-kothari

**Comment by Chrisha1212** [comment]
snehal Ingale-webdeveloperswj

**Comment by Chrisha1212** [comment]
Martin-Mathlucklala

**Comment by Chrisha1212** [comment]
Sunil Chauhan-mrsunilchauhan

**Comment by Chrisha1212** [comment]
Rajput Usman-Rajputusman

**Comment by Chrisha1212** [comment]
Pulkit Bajaj-pulkitbajaj007

**Comment by Chrisha1212** [comment]
Francisca Nwafor-@francaolisa

**Comment by Chrisha1212** [comment]
Kayode Babarinde-@KAYBABSGit

**Comment by Chrisha1212** [comment]
Kryptozero-jefferytnb

**Comment by Chrisha1212** [comment]
Benjamin-benjithorpe

**Comment by Francaolisa** [comment]
> Francisca Nwafor-@Francaolisa

I already sent you my GitHub username on slack. Pls check.
