### ISSUE TITLE
Contents for `Project Rules and Guidelines` page

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Management#237]
**Project System Update doc:** https://docs.google.com/document/d/1HoP6hAnNqk8WzdpjaCP17xP04eBsyJKkl_6rUSCcWy8/edit 
**Project rules page:** https://thenewboston.com/project-rules/overview

**Task:**
- Write updated content for [Project rules page](https://thenewboston.com/project-rules/overview) according to the new system.

**Comment by led76marx** [comment]
Reviewed and updated here; https://docs.google.com/document/d/1KTn4Zm3YgyIqremjB232gHZjPAbwXJEjRLukFEoDOIQ/edit#

**Comment by led76marx** [comment]
@manishram I was trying to re-assign it to you for review but it seems I can't. Let me know if this needs further work.
