### ISSUE TITLE
Review Team Page Sheet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#26]
Review this sheet to ensure there is no missing information https://docs.google.com/spreadsheets/d/1jodKH3l1n5fr8KDHMvsS-hUbahoLOWFokDIfFvUOF6I/edit?usp=sharing

**Comment by shaheerwasti** [comment]
Product Management is missing.

**Product Management Definition:** 
Product management in TNB is responsible for managing input, feedback, data from internal & external stakeholders. It ensures that the product is coordinated, documented, and organized to have a clear long-term direction. PM also have an important role in making the complexity of blockchain invisible for non-technical stakeholders. 

Addition of Slack channel: product-management

Repo link: https://github.com/thenewboston-developers/Management/
