### ISSUE TITLE
Accept Online Payments

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#35]
Design a payment processing system for websites/online stores to integrate with the network.

- separate nodes (benefit is won't mess with banks if bug in payment system, network becomes more complex is the downside)
- websockets to hook into banks
- banks will have services where websites can provide callbacks
- etc...

**Comment by shaheerwasti** [comment]
Needs the input from someone who understands [PCIDSS](https://www.itgovernance.co.uk/pci_dss). 
Payment processors might store cardholder data for converting TNBC to other currencies.

**Comment by buckyroberts** [comment]
![Online Payments](https://user-images.githubusercontent.com/8547538/102447984-f9722480-3fe5-11eb-88d2-0d81b5a2f180.png)
