### ISSUE TITLE
Browser extension wallet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#56]
Need to research how other browser extension wallets securely store signing key before development.

**Comment by colfax23** [comment]
We had a discussion about this during our blockchain research team meeting today.  Hargobind is starting to research this, using Metamask as a model.

**Comment by shaheerwasti** [comment]
The other day I was having a discussion with mrbusysky regarding this chain and he showed me that he might've already developed a similar extension to meta mask for TNBC wallet using `thenewboston-js` library. This was a news to me. 

[Image 1](https://drive.google.com/file/d/1TQ6vP_7tU2iOb6UVA8TAMG88OSy6zHMn/view?usp=sharing)
[Image 2](https://drive.google.com/file/d/1BtqKTP3RlU526FhqtSqj5bA1rg6mHR_J/view?usp=sharing)
[Image 3](https://drive.google.com/file/d/1Ww1Xdxwn02sqzfaSushWarm93JBwQibr/view?usp=sharing)

Now, I am not aware of the detailed technical aspect of it but I think, engineering and research can dig this further. We might've a ready to go software (browser extension) sitting in a shelve waiting to go live. One more thing he mentioned categorically, was this missing feature of *memos*. He said, and I quote, addition of messaging to transections is going to be a significant improvement for our chain and we will be able to connect online carts with this feature. Again! I can't comment on the technicalities of this but anything which is good from a business perspective interests Product Team.

**Comment by colfax23** [comment]
Awesome - I put mrbusysky in touch with Hargobind on my team to discuss this.  Thanks!

**Comment by mrbusysky** [comment]
This is already done it can be marked as complete
