### ISSUE TITLE
Remove Sunil Chauhan

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#63]
Remove Sunil Chauhan from the Marketing team as he is inactive. Will need to remove from both the `Payment-Processor` repo (to stop weekly payments) and also the Website.

**Comment by shaheerwasti** [comment]
@manishram is it possible to add/remove team members maybe using endpoint(s) such as https://api-dev.thenewboston.com/teams or any other way which lets us easily manage team members or contributors on website?

**Comment by manishram** [comment]
@shaheerwasti I think we can definitely manage team members easily once the backend is ready if I am not wrong. Currently, the site is static. 
Bucky can answer it better.

**Comment by buckyroberts** [comment]
@shaheerwasti @manishram Yep, the Website API including updated Teams logic is currently in development. Right now we just have to do things the dirty way.

**Comment by thesanjeevsharma** [comment]
@shaheerwasti ✔️ Removed. We can close this now.

**Comment by shaheerwasti** [comment]
Done!
