### ISSUE TITLE
Trustless standard

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#65]
Review Trustless standard doc provided by MrSky. If everything looks good we can add it to the website.

https://docs.google.com/document/d/1zWl2W5zUWbG45-eD21kaiMIYZaEOPa6rWUKsxJ-UJr8/edit?usp=sharing

@colfax23 @codedevloper @smash8tap

**Comment by colfax23** [comment]
Will do. I've set some time aside to do this tomorrow.

**Comment by colfax23** [comment]
There are a few things that are unclear to me.  Can you please grant edit access so I can add some comments? (I just put in a request)
