### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#66]
Dark mode/theme for the website

**Comment by sno2** [comment]
As we don't support older browsers, perhaps [darkmode.js](https://darkmodejs.learn.uno/#-using-npm) could work for us?  I don't have that much experience with React, though, so I don't think I could make a prototype.  Also, we could still tell if the page is in darkmode by the `darkmode--activated` class that is added to the `body` tag.  This would obviously have to be a scss mixin to style it.
