### ISSUE TITLE
CI/CI pipeline for Website API

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#67]
We are planning to start ramping up development on the Website-API repo and will require a more standardized development process. Here is a basic overview of what we have right now:

**Website**
- repo - https://github.com/thenewboston-developers/Website
- development - http://dev-thenewboston.s3-website-us-west-2.amazonaws.com/
- production - https://thenewboston.com/
- CD - from `development` to dev-thenewboston and `master` to thenewboston

**Website API**
- repo - https://github.com/thenewboston-developers/Website-API
- development - https://api-dev.thenewboston.com/
- production - https://api.thenewboston.com/
- CD - from `master` to both api-dev and api

---

I just created a new `development` branch on the Website-API repo and also added a branch protection rule to `master`. @shashanksinha89 can you work with @vosi to create a proper CD pipeline for deploying `development` to the api-dev environment for this Website-API repo? Then we develop off of that/populate with sample data/etc... and let `master` deploy only to our production api.

**Comment by vosi** [comment]
@shashanksinha89 I believe, we should follow an infrastructure as code approach, and deliver those changes as cloudformation template, i am adding you to the privat repository with an existing pipeline

**Comment by shashanksinha89** [comment]
PR raised. https://github.com/thenewboston-developers/infrastructure/pull/1
