### ISSUE TITLE
GitHub for Joe Sykes

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#70]
Reach out to Joe Sykes and get his GitHub username and profile photo. Then create a ticket in the Website repo to update that information.

<img width="870" alt="Screen Shot 2020-12-11 at 11 06 36 AM" src="https://user-images.githubusercontent.com/8547538/101944157-1ef3ce00-3ba1-11eb-9f5c-f1b73fa5e8fe.png">

**Comment by manishram** [comment]
This issue can be closed.
