### ISSUE TITLE
Add YouTube videos to website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#89]
Design - https://github.com/thenewboston-developers/Design/issues/137
Backend - https://github.com/thenewboston-developers/Website-API/issues/43
Frontend - https://github.com/thenewboston-developers/Website/issues/1282

**Comment by ma2b0043** [comment]
Design - thenewboston-developers/Design#137
Backend - thenewboston-developers/Website-API#43

have been completed, and have been marked as completed(ticket wise).

**Comment by ma2b0043** [comment]
Frontend - thenewboston-developers/Website#1282

however this^ has been completed but hasnt been give a ticket(tag) of being completed, so @buckyroberts kindly close this as well and see this issue for details as well.

**Comment by ma2b0043** [comment]
@angle943 @ThaDeveloper  based on what I have seen, this issue seems to be taken care of, should we close it now?

**Comment by angle943** [comment]
@ma2b0043 yeah I believe we just need to do the FE portion of it: https://github.com/thenewboston-developers/Website/issues/1282

@thesanjeevsharma will tackle that

**Comment by ma2b0043** [comment]
@angle943 thanks for the update. Will you close it when its completed or should I do it?

**Comment by angle943** [comment]
i'll prob forget to close this issue @ma2b0043 haha so you can do so once the FE portion of it is finished

**Comment by ma2b0043** [comment]
thats great!
